# Site settings
title: Alita's Blog
email: alita@ortizaggies.com
description: > # this means to ignore newlines until "baseurl:"
  Alita's Blog will be updated frequently with anything she wants.
  Her hobbies include crafting, hacking, math, singing and so much more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alita.ortizaggies.com" # the base hostname & protocol for your site
github_username:  l33ta

# Build settings
markdown: kramdown
